/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

package main

import "fmt"

func main() {
	sum := 2
	reg1 := 1
	reg2 := 2
	for true {
		newval := reg1 + reg2
		if newval > 4000000 {
			break
		} else if newval%2 == 0 {
			sum += newval
		}
		reg1 = reg2
		reg2 = newval
	}

	fmt.Println(sum)
}
